# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fangdong/work/cpkg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fangdong/work/cpkg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fangdong/work/cpkg/CMakeFiles /home/fangdong/work/cpkg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fangdong/work/cpkg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

cmd.o: cmd.c.o
.PHONY : cmd.o

# target to build an object file
cmd.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd.c.o
.PHONY : cmd.c.o

cmd.i: cmd.c.i
.PHONY : cmd.i

# target to preprocess a source file
cmd.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd.c.i
.PHONY : cmd.c.i

cmd.s: cmd.c.s
.PHONY : cmd.s

# target to generate assembly for a file
cmd.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd.c.s
.PHONY : cmd.c.s

cmd_addlibrary.o: cmd_addlibrary.c.o
.PHONY : cmd_addlibrary.o

# target to build an object file
cmd_addlibrary.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_addlibrary.c.o
.PHONY : cmd_addlibrary.c.o

cmd_addlibrary.i: cmd_addlibrary.c.i
.PHONY : cmd_addlibrary.i

# target to preprocess a source file
cmd_addlibrary.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_addlibrary.c.i
.PHONY : cmd_addlibrary.c.i

cmd_addlibrary.s: cmd_addlibrary.c.s
.PHONY : cmd_addlibrary.s

# target to generate assembly for a file
cmd_addlibrary.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_addlibrary.c.s
.PHONY : cmd_addlibrary.c.s

cmd_build.o: cmd_build.c.o
.PHONY : cmd_build.o

# target to build an object file
cmd_build.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_build.c.o
.PHONY : cmd_build.c.o

cmd_build.i: cmd_build.c.i
.PHONY : cmd_build.i

# target to preprocess a source file
cmd_build.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_build.c.i
.PHONY : cmd_build.c.i

cmd_build.s: cmd_build.c.s
.PHONY : cmd_build.s

# target to generate assembly for a file
cmd_build.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_build.c.s
.PHONY : cmd_build.c.s

cmd_version.o: cmd_version.c.o
.PHONY : cmd_version.o

# target to build an object file
cmd_version.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_version.c.o
.PHONY : cmd_version.c.o

cmd_version.i: cmd_version.c.i
.PHONY : cmd_version.i

# target to preprocess a source file
cmd_version.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_version.c.i
.PHONY : cmd_version.c.i

cmd_version.s: cmd_version.c.s
.PHONY : cmd_version.s

# target to generate assembly for a file
cmd_version.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cmd_version.c.s
.PHONY : cmd_version.c.s

compiler.o: compiler.c.o
.PHONY : compiler.o

# target to build an object file
compiler.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler.c.o
.PHONY : compiler.c.o

compiler.i: compiler.c.i
.PHONY : compiler.i

# target to preprocess a source file
compiler.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler.c.i
.PHONY : compiler.c.i

compiler.s: compiler.c.s
.PHONY : compiler.s

# target to generate assembly for a file
compiler.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler.c.s
.PHONY : compiler.c.s

compiler_gcc.o: compiler_gcc.c.o
.PHONY : compiler_gcc.o

# target to build an object file
compiler_gcc.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler_gcc.c.o
.PHONY : compiler_gcc.c.o

compiler_gcc.i: compiler_gcc.c.i
.PHONY : compiler_gcc.i

# target to preprocess a source file
compiler_gcc.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler_gcc.c.i
.PHONY : compiler_gcc.c.i

compiler_gcc.s: compiler_gcc.c.s
.PHONY : compiler_gcc.s

# target to generate assembly for a file
compiler_gcc.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/compiler_gcc.c.s
.PHONY : compiler_gcc.c.s

cpkg.o: cpkg.c.o
.PHONY : cpkg.o

# target to build an object file
cpkg.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cpkg.c.o
.PHONY : cpkg.c.o

cpkg.i: cpkg.c.i
.PHONY : cpkg.i

# target to preprocess a source file
cpkg.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cpkg.c.i
.PHONY : cpkg.c.i

cpkg.s: cpkg.c.s
.PHONY : cpkg.s

# target to generate assembly for a file
cpkg.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cpkg.c.s
.PHONY : cpkg.c.s

env.o: env.c.o
.PHONY : env.o

# target to build an object file
env.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/env.c.o
.PHONY : env.c.o

env.i: env.c.i
.PHONY : env.i

# target to preprocess a source file
env.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/env.c.i
.PHONY : env.c.i

env.s: env.c.s
.PHONY : env.s

# target to generate assembly for a file
env.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/env.c.s
.PHONY : env.c.s

package.o: package.c.o
.PHONY : package.o

# target to build an object file
package.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/package.c.o
.PHONY : package.c.o

package.i: package.c.i
.PHONY : package.i

# target to preprocess a source file
package.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/package.c.i
.PHONY : package.c.i

package.s: package.c.s
.PHONY : package.s

# target to generate assembly for a file
package.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/package.c.s
.PHONY : package.c.s

path.o: path.c.o
.PHONY : path.o

# target to build an object file
path.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/path.c.o
.PHONY : path.c.o

path.i: path.c.i
.PHONY : path.i

# target to preprocess a source file
path.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/path.c.i
.PHONY : path.c.i

path.s: path.c.s
.PHONY : path.s

# target to generate assembly for a file
path.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/path.c.s
.PHONY : path.c.s

str.o: str.c.o
.PHONY : str.o

# target to build an object file
str.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/str.c.o
.PHONY : str.c.o

str.i: str.c.i
.PHONY : str.i

# target to preprocess a source file
str.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/str.c.i
.PHONY : str.c.i

str.s: str.c.s
.PHONY : str.s

# target to generate assembly for a file
str.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/str.c.s
.PHONY : str.c.s

testunit.o: testunit.c.o
.PHONY : testunit.o

# target to build an object file
testunit.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testunit.c.o
.PHONY : testunit.c.o

testunit.i: testunit.c.i
.PHONY : testunit.i

# target to preprocess a source file
testunit.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testunit.c.i
.PHONY : testunit.c.i

testunit.s: testunit.c.s
.PHONY : testunit.s

# target to generate assembly for a file
testunit.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testunit.c.s
.PHONY : testunit.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cmd.o"
	@echo "... cmd.i"
	@echo "... cmd.s"
	@echo "... cmd_addlibrary.o"
	@echo "... cmd_addlibrary.i"
	@echo "... cmd_addlibrary.s"
	@echo "... cmd_build.o"
	@echo "... cmd_build.i"
	@echo "... cmd_build.s"
	@echo "... cmd_version.o"
	@echo "... cmd_version.i"
	@echo "... cmd_version.s"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
	@echo "... compiler_gcc.o"
	@echo "... compiler_gcc.i"
	@echo "... compiler_gcc.s"
	@echo "... cpkg.o"
	@echo "... cpkg.i"
	@echo "... cpkg.s"
	@echo "... env.o"
	@echo "... env.i"
	@echo "... env.s"
	@echo "... package.o"
	@echo "... package.i"
	@echo "... package.s"
	@echo "... path.o"
	@echo "... path.i"
	@echo "... path.s"
	@echo "... str.o"
	@echo "... str.i"
	@echo "... str.s"
	@echo "... testunit.o"
	@echo "... testunit.i"
	@echo "... testunit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

